heat_template_version: 2013-05-23
description: Simple template to deploy a single compute instance with parameters

parameters:
  key_name:
    type: string
    label: Key Name
    default: INF8480-TP3
    description: Name of key-pair to be used for compute instance
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: INF4410-Ubuntu-trusty-mini
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor
  network_id:
    type: string
    label: Network ID
    description: SCONETWORK Network to be used for the compute instance
    default: inf4410-net
    constraints:
      - custom_constraint: neutron.network
  external_network_id:
    type: string
    default: 0c3b1354-d3d5-4fec-86d3-19d4d1f13785
    description: UUID of a Neutron external network
    constraints:
      - custom_constraint: neutron.network

resources:

  my_instance:
    type: OS::Nova::Server
    properties:
      name: server_TP3_1
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
          - network: { get_param: network_id }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            wget "https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py"
            python server.py
          params:
            $db_name: database

  server_floating_ip_assoc:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: ip_float}
      server_id: {get_resource: my_instance}

  ip_float:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [my_instance, networks] }
